### ISSUE TITLE
同じ授業名で違う先生の場合

### ISSUE THREAD

**Issue by oyaoyaoya** [SugiKent/rikkyo_crawler#22]
## 例
経営学入門
[![https://gyazo.com/50afaf0e3f8cee971396cba143b0a781](https://gyazo.com/50afaf0e3f8cee971396cba143b0a781/raw)](https://gyazo.com/50afaf0e3f8cee971396cba143b0a781)
##

**Comment by SugiKent** [comment]
これは別授業として扱う

**Comment by SugiKent** [comment]
教室も違うし。

**Comment by SugiKent** [comment]
よって、なにもする必要はなし。
